Models/Cheese.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CheeseMVC.Models
{
    public class Cheese
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public CheeseType Type { get; set; }
        public int CheeseId { get; set; }
        private static int nextId = 1;

        public int Rating { get; set; }

        public Cheese()
        {
            CheeseId = nextId;
            nextId++;
        }
    }
}

Models/CheeseData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CheeseMVC.Models
{
    public class CheeseData
    {
        static private List<Cheese> cheeses = new List<Cheese>();

        // GetAll
        public static List<Cheese> GetAll()
        {
            return cheeses;
        }

        // Add
        public static void Add(Cheese newCheese)
        {
            cheeses.Add(newCheese);
        }

        // Remove
        public static void Remove(int id)
        {
            Cheese cheeseToRemove = GetById(id);
            cheeses.Remove(cheeseToRemove);
        }

        // GetById
        public static Cheese GetById(int id)
        {
            return cheeses.Single(x => x.CheeseId == id);
        }


    }
}

Models/CheeseType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CheeseMVC.Models
{
    public enum CheeseType
    {
        Hard, Soft , Fake
    }
}

Models/ErrorViewModel.cs
using System;

namespace CheeseMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ViewModels/AddCheeseViewModel.cs
using CheeseMVC.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;


namespace CheeseMVC.ViewModels
{
    public class AddCheeseViewModel
    {
        [Required]
        [Display(Name = "Cheese Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "You must give your cheese a description")]
        public string Description { get; set; }

        public CheeseType Type { get; set; }
        public List<SelectListItem> CheeseTypes { get; set; }
        [Required]
        [Range (1,5)]
        public int Rating { get; set; }
        public AddCheeseViewModel()
        {
            CheeseTypes = new List<SelectListItem>();
            CheeseTypes.Add(new SelectListItem
            {
                Value = ((int)CheeseType.Hard).ToString(),
                Text = CheeseType.Hard.ToString()
            });
            CheeseTypes.Add(new SelectListItem
            {
                Value = ((int)CheeseType.Soft).ToString(),
                Text = CheeseType.Soft.ToString()
            });
            CheeseTypes.Add(new SelectListItem
            {
                Value = ((int)CheeseType.Fake).ToString(),
                Text = CheeseType.Fake.ToString()
            });



        }

        public Cheese CreateCheese()
        {
            Cheese newCheese = new Cheese
            {
                Name = Name,
                Description = Description,
                Type = Type,
                Rating = Rating
            };
           
          return newCheese;
        }
    }
}

ViewModels/AddEditCheeseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CheeseMVC.ViewModels
{
    public class AddEditCheeseViewModel: AddCheeseViewModel
    {
        public int cheeseId { get; set; }
    }
}

Controllers/CheeseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CheeseMVC.Models;
using CheeseMVC.ViewModels;

namespace CheeseMVC.Controllers
{
    public class CheeseController : Controller
    {
        //public Dictionary<string, string> Cheeses.CheeseMVC(name , description ) ;
        //static private Dictionary<string, string> Cheeses = new Dictionary<string, string>();
        //static private List<string> Cheeses = new List<string>();
        

        public IActionResult Index()
        {

            List<Cheese> cheeses = CheeseData.GetAll();
            return View(cheeses);
        }
       
        public IActionResult Add()
        {
            AddCheeseViewModel addCheeseViewModel = new AddCheeseViewModel();
            return View(addCheeseViewModel);
        }

        public IActionResult Remove()
        {
            ViewBag.title = "Remove Cheeses";
            ViewBag.cheeses = CheeseData.GetAll();
            return View();
        }

        public IActionResult Delete()
        {
            ViewBag.cheeses = CheeseData.GetAll();
            return View();
        }

        [HttpPost]
        public IActionResult Add(AddCheeseViewModel addCheeseViewModel)
        {
            if (ModelState.IsValid)
            {
                Cheese mycheese = addCheeseViewModel.CreateCheese();
                CheeseData.Add(mycheese);
                return Redirect("/Cheese");
            }
            return View(addCheeseViewModel);
            
        }

        [HttpPost]
        [Route("/Cheese/Remove")]
        public IActionResult Remove(int[] cheeseIds)
        {
            

            //Remove a checked cheese
            foreach (int cheeseId in cheeseIds)

            {
                CheeseData.Remove(cheeseId); ;
            }
            
                        
            return Redirect("/");
        }

        [HttpPost]
        [Route("/Cheese/Delete")]
        public IActionResult DelCheese(int cheeseId)
        {
            //Delete the cheese using the select drop down list
            CheeseData.Remove(cheeseId);
            
            return Redirect("/Cheese");
        }
        //This is the get
        public IActionResult Edit(int cheeseId)
        {
            //https:localhost:44311/Cheese/Edit?cheeseId=1
            //int cheeseId = Request.QueryString["cheeseId"];

            AddEditCheeseViewModel addEditCheeseViewModel = new AddEditCheeseViewModel();
            Cheese cheeseToEdit = CheeseData.GetById(cheeseId);
            addEditCheeseViewModel.Name = cheeseToEdit.Name;
            addEditCheeseViewModel.Description = cheeseToEdit.Description;
            addEditCheeseViewModel.Type = cheeseToEdit.Type;
            addEditCheeseViewModel.cheeseId = cheeseToEdit.CheeseId;

            return View(addEditCheeseViewModel);
            
        }

        [HttpPost]
        [Route("/Cheese/Edit")]
        public IActionResult Edit (AddEditCheeseViewModel addEditCheeseViewModel)
        {
            
            Cheese myCheese = CheeseData.GetById(addEditCheeseViewModel.cheeseId);
            myCheese.Name = addEditCheeseViewModel.Name;
            myCheese.Description = addEditCheeseViewModel.Description;
            myCheese.Type = addEditCheeseViewModel.Type;

            return Redirect("/Cheese");
        }






        private static string validate(string name)
        {
            //string alphabeth = "abcdefghijklmnopqrstuvwxyz";
            string errors = "";
            if (name==null || name=="")
            {
                errors += "A name for the Cheese is needed";      
            }

            else if (name.Any(char.IsDigit))
            {
                errors += "A name cannot contain a number";
            }

            return errors;
        }

    }


}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CheeseMVC.Models;

namespace CheeseMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return Redirect("/Cheese");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Cheese/Add.cshtml
@{
//Layout = _Layout.cs;

}



<form method="post">
    <input type="text" name="name" placeholder=" Name"/>
    <input type="text" name="description" placeholder="Description"/> 
    <input type ="submit" value="Add Cheese" />

</form>

Views/Cheese/Delete.cshtml
    <form name="delSelect" method="post">
        <select name="cheeseId">
            @foreach (var cheese in ViewBag.cheeses)
            {
                <option name="@cheese.Name" id="@cheese.CheeseId" value="@cheese.CheeseId"> @cheese.Name</option>
            }
        </select>
            <input type="submit" value="Delete Cheese" />

        </form>

Views/Cheese/Edit.cshtml
@model CheeseMVC.ViewModels.AddEditCheeseViewModel

<h1> Edit Cheese</h1>

<form asp-controller="Cheese" asp-action="Edit" method="post">
    <!--<div asp-validation-summary="All">
    </div>-->
    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />

        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input class="form-control" asp-for="Description" />
        <span asp-validation-for="Description"></span>
    </div>
    <div class="form-group">
        <label asp-for="Type"></label>
        <select asp-for="Type" asp-items="Model.CheeseTypes"></select>

    </div>
    <div class="form-group">
        <label asp-for="Rating"></label>
        <input class="form-control" asp-for="Rating" />
        <span asp-validation-for="Rating"></span>
    </div>

    <input type="hidden" name="cheeseId" value="@Model.cheeseId" />
    <input type="submit" value="Edit Cheese" />
</form>

Views/Cheese/Index.cshtml
@model List<CheeseMVC.Models.Cheese>


<h1>@ViewBag.Title</h1>
<p>
    <a asp-controller="Cheese" asp-action="Add">Add Cheese </a><br />
    <a asp-controller="Cheese" asp-action="Remove">Remove Cheese Checkbox </a><br />
    <a asp-controller="Cheese" asp-action="Delete">Delete Cheese Select </a>


</p>

@if (Model.Count == 0)
{
    <p>No cheeses yet!</p>  
}

<table class="table">
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Type</th>
        <th>Rating</th>
    </tr>

    @foreach (var cheese in Model)
    {
<tr>
    <td>@cheese.Name</td>
    <td>@cheese.Description</td>
    <td>@cheese.Type</td>
    <td>@cheese.Rating</td>
    <td><a asp-controller="Cheese" asp-action="Edit" asp-route-cheeseId="@cheese.CheeseId">Edit</a></td>
</tr>
        
    }
</table>

@if (ViewBag.error != null)
{
    <p>@ViewBag.error</p>
}

Views/Cheese/Remove.cshtml
<h1>@ViewBag.title</h1>

<form method="post">

    @foreach (var cheese in ViewBag.cheeses)
    {
        <input type="checkbox" name="cheeseIds" id="@cheese.CheeseId" value="@cheese.CheeseId" />
        <label for="@cheese.CheeseId">@cheese.Name</label>
        <br />
    }

    <input type="submit" value="Remove Selected Cheese(s)" />
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CheeseMVC</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CheeseMVC</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Cheese" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Cheese" asp-action="Add">Add</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - CheeseMVC</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>